<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFileContent</value>
  <value name="spec">wx.pgp.specifications:getFileContentSpec</value>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBHZXQgaW5wdXQNCklEYXRhQ3Vyc29yIHBjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpT
dHJpbmcgcGF0aCA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGMsICJwYXRoIik7DQpTdHJpbmcgZW5j
b2RpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBjLCAiZW5jb2RpbmciKTsNCg0KLy8gVmFsaWRh
dGUgaW5wdXQNCmlmIChwYXRoID09IG51bGwgfHwgcGF0aC5lcXVhbHMoIiIpKSB7DQogICAgdGhy
b3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlBhdGggY2Fubm90IGJlIGVtcHR5Iik7DQp9DQppZiAo
ZW5jb2RpbmcgPT0gbnVsbCB8fCBlbmNvZGluZy5lcXVhbHMoIiIpKSB7DQogICAgZW5jb2Rpbmcg
PSAiVVRGLTgiOw0KfSBlbHNlIGlmICghQ2hhcnNldC5pc1N1cHBvcnRlZChlbmNvZGluZykpIHsN
CiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiVW5zdXBwb3J0ZWQgY2hhcmFjdGVyIGVu
Y29kaW5nIik7DQp9DQoNCi8vIFJlYWQgZmlsZSANCkZpbGVJbnB1dFN0cmVhbSBpbiA9IG51bGw7
DQpCeXRlQXJyYXlPdXRwdXRTdHJlYW0gb3V0ID0gbnVsbDsNCnRyeSB7DQogICAgaW4gPSBuZXcg
RmlsZUlucHV0U3RyZWFtKG5ldyBGaWxlKHBhdGgpKTsNCiAgICBvdXQgPSBuZXcgQnl0ZUFycmF5
T3V0cHV0U3RyZWFtKCk7DQogICAgYnl0ZVtdIGJ1ZmZlciA9IG5ldyBieXRlWzgxOTJdOw0KICAg
IGludCByZWFkID0gMDsNCiAgICB3aGlsZSAoKHJlYWQgPSBpbi5yZWFkKGJ1ZmZlcikpID4gMCkg
ew0KICAgICAgICBvdXQud3JpdGUoYnVmZmVyLCAwLCByZWFkKTsNCiAgICB9DQogICAgb3V0LmZs
dXNoKCk7DQogICAgSURhdGFVdGlsLnB1dChwYywgImNvbnRlbnQiLCBvdXQudG9TdHJpbmcoZW5j
b2RpbmcpKTsNCn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQogICAgdGhyb3cgbmV3IFNlcnZpY2VF
eGNlcHRpb24oIlVuYWJsZSB0byByZWFkIGZpbGUgY29udGVudCIpOw0KfSBmaW5hbGx5IHsNCiAg
ICB0cnkgew0KICAgICAgICBpbi5jbG9zZSgpOw0KICAgICAgICBvdXQuY2xvc2UoKTsNCiAgICB9
IGNhdGNoIChFeGNlcHRpb24gZSkge30NCn0NCnBjLmRlc3Ryb3koKTsNCg0K</value>
</Values>
